# WeebSync Local Docker Setup

services:
  weebsync:
    build:
      context: .
      dockerfile: Dockerfile
    image: weebsync:local
    container_name: weebsync
    ports:
      - "42380:42380"
    environment:
      NODE_ENV: production
      WEEB_SYNC_SERVER_HTTP_PORT: 42380
    volumes:
      # Mount config with write permissions since app needs to create files
      - ./server/config:/app/config
      # Mount plugins directory for custom plugins
      - ./plugins:/app/plugins
      - weebsync-data:/app/data

      # Media volume examples - uncomment and adjust paths as needed:
      # - /path/to/your/anime:/media/anime
      # - /path/to/your/movies:/media/movies
      # - /path/to/downloads:/downloads
      # - /mnt/media-drive:/media
      # - /Volumes/ExternalDrive:/external
    restart: unless-stopped

volumes:
  weebsync-data:
